### ISSUE TITLE
returns an empty promise object

### ISSUE THREAD

**Issue by adidasnike90** [domoritz/clingo-wasm#137]
Dear Author,
I am trying to use clingo-wasm in a codesandbox project, but could not get it work.

I simply tested it this way:

const clingo = require("clingo-wasm");
clingo.run("a. b :- a.").then(console.log);

Nothing can be printed on the console.

Thanks,
Fang

**Comment by domoritz** [comment]
Can you send a link to the code sandbox?

**Comment by adidasnike90** [comment]
Hi Domoritz,
Here is the test case: https://codesandbox.io/s/admiring-river-quj8u?file=/src/App.js

**Comment by domoritz** [comment]
It looks like the wasm isn't instantiated correctly.

<img width="721" alt="Screen Shot 2021-10-03 at 21 35 18" src="https://user-images.githubusercontent.com/589034/135781507-c233dc23-79fe-40e6-a2b2-828834ff08a1.png">
 
Since https://domoritz.github.io/clingo-wasm/ works, I suspect the issue is in the setup and not this library.

**Comment by adidasnike90** [comment]
Thank you so much!
