### ISSUE TITLE
Client side WASM compilation issue

### ISSUE THREAD

**Issue by Markusdreyer** [domoritz/clingo-wasm#185]
Hello again, 

I'm having some issues with running WASM in the browser. I'm trying to run the browser example with the following HTML file:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/clingo-wasm@0.0.10/dist/clingo.web.min.js"></script>
  </head>
  <body>
    <script>
      async function main() {
        await clingo.init(
          "https://cdn.jsdelivr.net/npm/clingo-wasm@VERSION/dist/clingo.wasm"
        );
        console.log(await clingo.run("a. b :- a."));
      }

      main();
    </script>
  </body>
</html>

```

However, I'm getting the following RuntimeError in the console:
```
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
```

I'm not familiar with WASM, but it seems to expect some magic word to identify the WASM module. However, the actual word was `3c 21 44 4f`, which is `<!DOC` in ASCII. This indicates that the actual file is HTML. Is this a familiar issue? I was sure I'd gotten WASM to work client-side before with React, but I'm getting the same issue there. I tried a few different versions (0.0.10, 0.0.9, 0.0.8, 0.0.6) all with the same issue.

**Comment by domoritz** [comment]
Replace @version with the actual version number.

**Comment by Markusdreyer** [comment]
Ah, wow. I forgot to update the second CDN reference 😅  Thanks!

**Comment by Markusdreyer** [comment]
I thought I had it figured out, but it seems I'm still having some client-side issues. Updating the HTML above with _version_ solved the problem for the HTML file, but I'd like to test it out in React and the npm. The following code runs fine in Node:
```
import * as clingo from "clingo-wasm";

await clingo.run("a. b :- a.")
```

However, running the same code client-side yields the error mentioned in the original post: 
```
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
```

**Comment by domoritz** [comment]
That's sounds like an issue with react/bundling/the app setup to me. Do you agree?

**Comment by Markusdreyer** [comment]
Unsure, not unlikely. If this isn't a familiar issue I'll have a go at it and see if I can find the cause.

**Comment by domoritz** [comment]
Have you checked the wasm file in the inspector?

**Comment by domoritz** [comment]
Closing since this looks like an issue outside this library.

**Comment by peter-gy** [comment]
Hey @Markusdreyer, I am not sure whether this issue is still relevant for you, but I have encountered the same problem while working on peter-gy/visrecly#11 and would like to share my findings with you - or simply leave it here as a future reference.

As the author outlined, this is indeed a build issue, but given that I recently spent some time debugging this, I can elaborate on it in a bit more detail. *Spoiler: the error message is actually helpful, it is just rather cryptic.*

### Short Explanation

You should configure your build tool to expose `clingo.wasm` as a public artefact of your application so that it can be accessed via an URL such as `http://localhost:4200/dist/clingo.wasm`. Then, you should configure this module by calling the `init` function from [`index.web.ts`](https://github.com/domoritz/clingo-wasm/blob/master/src/index.web.ts#L28) which takes a `wasmUrl` string parameter exactly for this purpose.

### Long Explanation

The error message states that it expects the magic word `00 61 73 6d`. This is a peculiarity of the `wasm` binary format, it always opens with the 4-byte magic string `"\0asm"`. If you convert the HEX `00 61 73 6d` to ASCII to make it human-readable, you will see, that the error message simply says: `expected magic word "\0asm"`.

The second part of the error message is somewhat more interesting. Following the same approach, converting HEX to ASCII, one can realize that `3c 21 44 4f` stands for `<!DO` as in `<!DOCTYPE html>`. Note that you only get `3c 21 44 4f == <!DO` in the error message of `WebAssembly.instantiate()`, since your browser attempts to compile the `wasm` module, and it starts with a format checking, looking for the `"\0asm"` magic word in HEX, hence, it shows you the diff of the first 4 bytes only.

What this really means is that the URL from which the `clingo.wasm` module is being accessed for the initialization actually leads to an HTML file, most likely to an auto-generated 404-page (this is what happened in my case). An HTML file is of course useless for the initialization of a WebAssembly module, hence the error. One can verify this using the browser's network inspector (as the author also suggested in [this](https://github.com/domoritz/clingo-wasm/issues/185#issuecomment-1059115281) answer):

<img width="779" alt="Screenshot 2022-08-05 at 23 43 47" src="https://user-images.githubusercontent.com/40776291/183213911-f2531e64-e79d-4115-af67-a01c0e26d5ea.png">

The solution for this - as explained in the *Short Explanation* - would be to make sure that the URL through which `clingo.wasm` is being accessed indeed points to the `wasm` file.

Alternatively, one can keep calling the module from `node`. Fortunately, I am able to do so, thanks to the fact that I am building my project with Next.js, allowing mixing and matching client-side and server-side rendering.
